Server on port 3000
DB is conected
(node:8896) UnhandledPromiseRejectionWarning: ReferenceError: User is not defined
    at router.post (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\src\routes\users.js:31:27)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:335:1dex.js:284:7ter\index.js:275:10)
    at Function.process_params (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_moduess\lib\router\index.js:174:3)les\express\lib\router\index.js:335:12)outer\index.js:47:12)
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\rounode_modules\express\lib\router\layerter\index.js:275:10)lib\router\index.js:317:13)
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:284:7dex.js:635:15les\express\lib\router\index.js:335:1
(node:8896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originatter\index.js:275:10)ed either by throwing inside of an async function without a catch block, or by rejecting a prodex.js:635:15mise which was not handled with .catch(). (rejection id: 1)ed either by throwing inside of an as
(node:8896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-future, promise rejections that are nzero exit code.
(node:8896) UnhandledPromiseRejectionWarning: ReferenceError: User is not defined
    at router.post (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\src\routes\users.js:31:27)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:635:15
(node:8896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)


Server on port 3000
DB is conected 
(node:12212) UnhandledPromiseRejectionWarning: ReferenceError: User is not defined
    at router.post (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\src\routes\users.js:32:27)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer.js:95:5) 
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer.js:95:5) 
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:335:12)        
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\layer.js:95:5) 
    at trim_prefix (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:335:12)        
    at next (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\node_modules\express\lib\router\index.js:635:15
(node:12212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Server on port 3000
DB is conected
(node:9672) UnhandledPromiseRejectionWarning: TypeError: user.matchPassword is not a function 
    at Strategy.passport.use.LocalStrategy [as _verify] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\src\config\passport.js:16:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async 
function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9672) UnhandledPromiseRejectionWarning: TypeError: user.matchPassword is not a function
    at Strategy.passport.use.LocalStrategy [as _verify] (C:\Users\aaspe\Desktop\Py-curso\05_Fazt_node_mongodb\src\config\passport.js:16:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async 
function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)